import type { Metadata } from "next";
import { Signika } from 'next/font/google'
import "./globals.css";
import Header from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";

const inter = Signika({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CodePandas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "transparent" }}>
        <main id="main-content">
          <Header pathname="test" />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
